// apps/lisk-angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'lisktest-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  title = 'lisk-angular';

  JSON = JSON;

  value = {
    text: 'text in angular component'
  }

  clicked(event: Event) {
    console.log(event)
  }
}

<div class="flex justify-center pt-10">
  <div class="p-5 max-w-sm text-center border rounded-lg shadow-md">
    <h1 class="text-4xl text-green-800 mb-4">Angular App</h1>
    <ui-element [attr.data-value]="JSON.stringify(value)" (clicked)="clicked($event)"></ui-element>
  </div>
</div>

// apps/lisk-react/src/app/app.tsx
import { useRef, useEffect } from 'react';
import { UIElement } from '@lisktest/ui';

export function App() {
  const value = {
    text: 'text in React component',
  };

  const uiel = useRef<UIElement>(null);

  const onClick = (e: Event) => {
    console.log(e);
  };

  useEffect(() => {
    if (uiel.current) {
      uiel.current.addEventListener('clicked', onClick);
    }
    return () => {
      if (uiel.current) {
        uiel.current.removeEventListener('clicked', onClick);
      }
    };
  });

  return (
    <div className="flex justify-center pt-10">
      <div className="p-5 max-w-sm text-center border rounded-lg shadow-md">
        <h1 className="text-4xl text-green-800">React App</h1>
        <ui-element ref={uiel} data-value={JSON.stringify(value)} onClicked={onClick}></ui-element>
      </div>
    </div>
  );
}

export default App;
